replicaCount: 2

image:
  repository: wwppk/myapp:v2

service:
  type: NodePort
  port: 9000

postgresql:
  enabled: true
  postgresqlUsername: myuser
  postgresqlPassword: passwd
  postgresqlDatabase: myapp
  service:
    port: "5432"
