apiVersion: skaffold/v2beta1
kind: Config
build:
  tagPolicy:
    sha256: {}
  artifacts:
  - image: wwppk/myapp
    context: hello-py
deploy:
  helm:
    releases:
    - name: hello-skaffold
      chartPath: hello-chart
      values:
        image: wwppk/myapp
